# Generated by Django 5.0.6 on 2024-06-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navoisite', '0003_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
