# Generated by Django 5.0.3 on 2024-06-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navoisite', '0005_elon_alter_newsarticle_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
